server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a1local?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有Entity别名类所在的包
  type-aliases-package: com.atguigu.springcloud.entities

# 通过logging.config属性指定logback配置文件 ---> 保证先加载application再读取logback配置文件，解决读取logback时缺少日志存放地址属性
logging:
  config: classpath:logback-custom.xml

# 自定义日志文件配置属性
log:
  # 日志存储路径
  logName: E:/project/java/springCloud/cloud2020/log/cloud_provider_payment8001

# Eureka_client配置
eureka:
  client:
    # 表示向注册中心注册自己
    register-with-eureka: true
    # 表示会去抓取服务自己的注册信息,默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 此处对应 cloud-eureka-server7001 项目 application.yml 中配置的 defaultZone
      # defaultZone: http://localhost:7001/eureka
      # 集群版需添加全部eureak地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

