server:
  port: 80

spring:
  application:
    # 此服务名称也在Eureka中使用
    name: cloud-order—feign-hystrix-service

# 通过logging.config属性指定logback配置文件 ---> 保证先加载application再读取logback配置文件，解决读取logback时缺少日志存放地址属性
logging:
  config: classpath:logback-custom.xml
  # feign日志以什么级别 监控哪个接口
  level:
    com.atguigu.springcloud.fegin.ServiceFeign: debug

# 自定义日志文件配置属性
log:
  # 日志存储路径
  logName: E:/project/java/springCloud/cloud2020/log/cloud-consumer-feign-hystrix-order80

# Eureka_client配置
eureka:
  client:
    # 表示向注册中心注册自己
    register-with-eureka: true
    # 表示会去抓取服务自己的注册信息,默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 此处对应 cloud-eureka-server7001 项目 application.yml 中配置的 defaultZone
       defaultZone: http://localhost:7001/eureka
      # 集群版需添加全部eureak地址
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    # 修改在eureka页面上显示的服务名称
    instance-id: orderFeignHystrix80
    # eureka页面上鼠标放入项目名称上有ip提示
    prefer-ip-address: true

##设置feign客户端超时时间( openFeign默认支持ribbon)
feign:
  client:
    config:
      default:
        #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
        ConnectTimeout: 5000
        #指的是建立连接后从服务器读取到可用资源所用的时间
        ReadTimeout: 5000
  #openFeign集成了hystrix 若要在客户端开启hystrix 进行下设置
  #hystrix默认响应时间为1s 和 上ReadTimeout 一样需要进行设置 否则在服务端开启hystrix时 调用超时测试方法时会现实超时
#  hystrix:
#    enabled: true

