server:
  port: 7001

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名字
    hostname: eureka7001.com
  client:
    # 表示不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    # 集群情况下，不再填写自己，填写其他eureka服务地址 多台情况使用,隔开
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

# 通过logging.config属性指定logback配置文件 ---> 保证先加载application再读取logback配置文件，解决读取logback时缺少日志存放地址属性
logging:
  config: classpath:logback-custom.xml

# 自定义日志文件配置属性
log:
  # 日志存储路径
  logName: E:/project/java/springCloud/cloud2020/log/cloud_eureka_7001