server:
  port: 7001

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名字
    hostname: localhost
  client:
    # 表示不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/