server:
  port: 80

spring:
  application:
    # 此服务名称也在Eureka中使用
    name: cloud-order-feign-service

# 通过logging.config属性指定logback配置文件 ---> 保证先加载application再读取logback配置文件，解决读取logback时缺少日志存放地址属性
logging:
  config: classpath:logback-custom.xml

# 自定义日志文件配置属性
log:
  # 日志存储路径
  logName: E:/project/java/springCloud/cloud2020/log/cloud-consumer-order-order80

# Eureka_client配置
eureka:
  client:
    # 表示向注册中心注册自己
    register-with-eureka: true
    # 表示会去抓取服务自己的注册信息,默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 此处对应 cloud-eureka-server7001 项目 application.yml 中配置的 defaultZone
      # defaultZone: http://localhost:7001/eureka
      # 集群版需添加全部eureak地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    # 修改在eureka页面上显示的服务名称
    instance-id: orderFeign80
    # eureka页面上鼠标放入项目名称上有ip提示
    prefer-ip-address: true